stages:
- stage: Build
  jobs:
  - job: Build
    pool:
      vmImage: 'Ubuntu-16.04'
    continueOnError: true
    steps:
    - script: echo "hello to my first Build"
    - task: aquasecScanner@4
      inputs:
        image: 'Ubuntu'
        scanType: 'local'
        register: false
        hideBase: false
        showNegligible: false
        windowsScannerVersion: '4.2.0'
        registry: 'Docker Hub'
        connection: 'Aqua Demo Console Jake'
        caCertificates: true